apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwa-deployment
  labels:
    app: pwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwa
  template:
    metadata:
      labels:
        app: pwa
    spec:
      containers:
      - name: pwa
        image: blatsosinf/pwa-img:latest 
        ports:
        - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: pwa-app-service
spec:
  type: NodePort
  selector:
    app: pwa
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
      nodePort: 30200
